# Generated by Django 5.2 on 2025-04-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video',
        ),
    ]
